# Sohybe Ibrahim Abdelwahab Amer
## 222250182

In [24]:
import pandas as pd

In [25]:
df = pd.read_excel("Task5-asset.xlsx")

In [27]:
inputs = df.drop('salary_more_then_100k',axis='columns')

In [28]:
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [29]:
inputs

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [30]:
target = df['salary_more_then_100k']

In [31]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

# -------------- Edited from here --------------
## Added train-test split for the data to get the accuracy of the test set and added the gini criterion to compare it with entropy.

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target, train_size=0.8, test_size=0.2, random_state=42)

In [43]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [89]:
X_train = X_train.copy()
X_test = X_test.copy()

X_train['company_n'] = le_company.fit_transform(X_train['company'])
X_train['job_n'] = le_job.fit_transform(X_train['job'])
X_train['degree_n'] = le_degree.fit_transform(X_train['degree'])

X_test['company_n'] = le_company.transform(X_test['company'])
X_test['job_n'] = le_job.transform(X_test['job'])
X_test['degree_n'] = le_degree.transform(X_test['degree'])

In [92]:
X_train

       company                  job     degree  company_n  job_n  degree_n
13    facebook     business manager    masters          1      0         1
11    facebook      sales executive    masters          1      2         1
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
2       google     business manager  bachelors          2      0         0
15    facebook  computer programmer    masters          1      1         1
4       google  computer programmer  bachelors          2      1         0
7   abc pharma  computer programmer  bachelors          0      1         0
10    facebook      sales executive  bachelors          1      2         0
12    facebook     business manager  bachelors          1      0         0
3       google     business manager    masters          2      0         1
6   abc pharma      sales executive    masters          0      2         1

In [96]:
X_train_clean = X_train.drop(['company', 'job', 'degree'], axis=1)
X_test_clean = X_test.drop(['company', 'job', 'degree'], axis=1)

In [97]:
X_train_clean

    company_n  job_n  degree_n
13          1      0         1
11          1      2         1
8           0      0         0
9           0      0         1
2           2      0         0
15          1      1         1
4           2      1         0
7           0      1         0
10          1      2         0
12          1      0         0
3           2      0         1
6           0      2         1

In [98]:
y_train

13    1
11    1
8     0
9     1
2     1
15    1
4     0
7     0
10    1
12    1
3     1
6     0
Name: salary_more_then_100k, dtype: int64

In [99]:
from sklearn import tree
# model = tree.DecisionTreeClassifier()
# default is "gini"

In [100]:
model_ent = tree.DecisionTreeClassifier(criterion ="entropy")
model_gini = tree.DecisionTreeClassifier(criterion ="gini")
# using ID3

In [101]:
model_ent.fit(X_train_clean, y_train)
model_gini.fit(X_train_clean, y_train)

DecisionTreeClassifier()

In [102]:
model_ent.score(X_train_clean,y_train)

1.0

In [103]:
model_gini.score(X_train_clean,y_train)

1.0

In [104]:
model_ent.predict([[2,1,0]])

C:\Users\HYBE\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [105]:
model_gini.predict([[2,1,0]])

C:\Users\HYBE\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [106]:
model_ent.predict([[2,1,1]])

C:\Users\HYBE\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [107]:
model_gini.predict([[2,1,1]])

C:\Users\HYBE\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

# Task
# Get the Accuracy of Decision Tree
# Brief description between gini and entropy

# Solution:

## Accuracy of decistion tree (after splitting the data earlier to get the accuracy of the test set):

In [109]:
accuracy_ent = model_ent.score(X_test_clean, y_test)

In [111]:
accuracy_gini = model_gini.score(X_test_clean, y_test)

In [112]:
print(f"The accuracy using entropy is: {accuracy_ent} and the accuracy using gini is: {accuracy_gini}")

The accuracy using entropy is: 0.75 and the accuracy using gini is: 0.75

In machine learning, Gini Impurity and Entropy are both metrics used to measure the "disorder" or "impurity" in a dataset. They help a Decision Tree decide which feature provides the best split at each node.

1. Mathematical Rules


Gini Impurity$$G = 1 - \sum_{i=1}^{n} (p_i)^2$$Entropy$$H = -\sum_{i=1}^{n} p_i \log_2(p_i)$$

2. Core Differences


Computational Complexity: Gini is faster to calculate because it only involves squaring probabilities. Entropy is more computationally expensive because it requires calculating a logarithm ($\log_2$). Sensitivity: Entropy is slightly more sensitive to changes in node probabilities than Gini. This means it often results in more "balanced" trees, whereas Gini tends to isolate the most frequent class into its own branch. Resulting Trees: In most practical cases, both metrics produce very similar trees. If you are working on a large-scale project where performance matters, Gini is usually the preferred default.